### ISSUE TITLE
txt2tei.py misspells revisionDesc

### ISSUE THREAD

**Issue by cmil** [fsanzl/txt2tei#1]
https://github.com/fsanzl/txt2tei/blob/ff303576785db948d19f564541f9c9e85e427864/txt2tei/txt2tei.py#L139 

txt2tei.py creates an element `RevisionDesc` which [according to the TEI standard](https://tei-c.org/release/doc/tei-p5-doc/de/html/ref-revisionDesc.html) would need to be spelled `revisionDesc`.

**Comment by fsanzl** [comment]
Solved
