### ISSUE TITLE
Invalid date format in 'when' attributes

### ISSUE THREAD

**Issue by cmil** [fsanzl/txt2tei#2]
The date format used for `when` attributes here

https://github.com/fsanzl/txt2tei/blob/ff303576785db948d19f564541f9c9e85e427864/txt2tei/txt2tei.py#L110

and here

https://github.com/fsanzl/txt2tei/blob/ff303576785db948d19f564541f9c9e85e427864/txt2tei/txt2tei.py#L141

does not conform to the W3C XML Schema Part 2: Datatypes Second Edition. See https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.datable.w3c.html for examples of valid date time values.

**Comment by fsanzl** [comment]
Solved
